# Generated by Django 5.0.1 on 2024-01-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0007_alter_uploadcv_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/blog_img/'),
        ),
        migrations.AlterField(
            model_name='uploadcv',
            name='upload',
            field=models.FileField(upload_to='static/cv_pdfs/'),
        ),
    ]
