# Generated by Django 5.0.1 on 2024-01-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0008_blogmodel_image_alter_uploadcv_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='descriptions',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='descriptions',
            field=models.TextField(max_length=5000),
        ),
    ]
