# Generated by Django 5.0.1 on 2024-01-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0009_alter_blogmodel_descriptions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='static/blog_img/')),
                ('name', models.CharField(max_length=100)),
                ('descriptions', models.TextField(max_length=5000)),
            ],
        ),
    ]
