# Generated by Django 5.0.1 on 2024-01-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0011_projectmodel_image_projectmodel_link_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('Message', models.TextField(max_length=2000)),
            ],
        ),
    ]
